name: Django CI

# 変なインデントや使用していないimport等を防ぐ

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHubのリポジトリからコードを持ってくる
      - uses: actions/checkout@4

      # 2. Python環境を作成
      - name: St up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # バージョンに合わせる

      # 3. ライブラリのインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # 4. コードスタイルチェック (Link)
      # E501などは一旦無視
      - name: Link with flake8
        run: |
          flake8 . --count --select=E9, F63, F7, F82 -- show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics